server:
  port: 9091

spring:
  data:
    mongodb:
      database: ${env.MONGO_DATABASE}
      uri: mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}


  application:
    name: User-Service
    
  cloud:
    gateway:
      routes:
        
      - id: TRAIN-SERVICE
        uri: lb://TRAIN-SERVICE
        predicates:
        - Path=/api/v1/train/**
        
      - id: BUS-SERVICE
        uri: lb://BUS-SERVICE
        predicates:
        - Path=/api/v1/bus/**
        
      - id: FLIGHT-SERVICE
        uri: lb://FLIGHT-SERVICE
        predicates:
        - Path=/api/v1/flight/**
        
        
      - id: BOOKING-SERVICE
        uri: lb://BOOKING-SERVICE
        predicates:
        - Path=/api/v1/booking/** 
         
  main:
    web-application-type: reactive
    
  

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8761/eureka
     instance:     
     hostname: localhost
     
     



     
